// <auto-generated />
using System;
using BTapDay09_CodeFirst.BusinessModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTapDay09_CodeFirst.Migrations
{
    [DbContext(typeof(LtynQLBHContext))]
    [Migration("20251017162041_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynCt_HoaDon", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<double?>("ltynDonGiaMua")
                        .HasColumnType("float");

                    b.Property<int?>("ltynHoaDonID")
                        .HasColumnType("int");

                    b.Property<int?>("ltynSanPhamID")
                        .HasColumnType("int");

                    b.Property<int?>("ltynSoLuongMua")
                        .HasColumnType("int");

                    b.Property<double?>("ltynThanhTien")
                        .HasColumnType("float");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.HasIndex("ltynHoaDonID");

                    b.HasIndex("ltynSanPhamID");

                    b.ToTable("LtynCT_HOA_DON");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynHoaDon", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<string>("ltynDiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ltynEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynHoTenKhachHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynMaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ltynMaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ltynNgayHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ltynNgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ltynTongTriGia")
                        .HasColumnType("float");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.HasIndex("ltynMaKhachHang");

                    b.ToTable("LtynHOA_DON");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynKhachHang", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<string>("ltynDiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ltynEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynHoTenKhachHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynMaKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ltynMatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ltynNgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.ToTable("LtynKHACH_HANG");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynLoaiSanPham", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<string>("ltynMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ltynTenLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.ToTable("LtynLOAI_SAN_PHAM");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynQuanTri", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<string>("ltynHoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynMatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ltynTenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.ToTable("LtynQUAN_TRI");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynSanPham", b =>
                {
                    b.Property<int>("ltynID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ltynID"));

                    b.Property<double?>("ltynDonGia")
                        .HasColumnType("float");

                    b.Property<string>("ltynHinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ltynMaLoai")
                        .HasColumnType("int");

                    b.Property<string>("ltynMaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ltynSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ltynTenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("ltynTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ltynID");

                    b.HasIndex("ltynMaLoai");

                    b.ToTable("LtynSAN_PHAM");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynCt_HoaDon", b =>
                {
                    b.HasOne("BTapDay09_CodeFirst.Models.DataModels.LtynHoaDon", "LtynHoaDon")
                        .WithMany("LtynCt_HoaDons")
                        .HasForeignKey("ltynHoaDonID");

                    b.HasOne("BTapDay09_CodeFirst.Models.DataModels.LtynSanPham", "LtynSanPham")
                        .WithMany("LtynCt_HoaDons")
                        .HasForeignKey("ltynSanPhamID");

                    b.Navigation("LtynHoaDon");

                    b.Navigation("LtynSanPham");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynHoaDon", b =>
                {
                    b.HasOne("BTapDay09_CodeFirst.Models.DataModels.LtynKhachHang", "LtynKhachHang")
                        .WithMany("LtynHoaDons")
                        .HasForeignKey("ltynMaKhachHang");

                    b.Navigation("LtynKhachHang");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynSanPham", b =>
                {
                    b.HasOne("BTapDay09_CodeFirst.Models.DataModels.LtynLoaiSanPham", "LtynLoaiSanPham")
                        .WithMany("LtynSanPhams")
                        .HasForeignKey("ltynMaLoai");

                    b.Navigation("LtynLoaiSanPham");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynHoaDon", b =>
                {
                    b.Navigation("LtynCt_HoaDons");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynKhachHang", b =>
                {
                    b.Navigation("LtynHoaDons");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynLoaiSanPham", b =>
                {
                    b.Navigation("LtynSanPhams");
                });

            modelBuilder.Entity("BTapDay09_CodeFirst.Models.DataModels.LtynSanPham", b =>
                {
                    b.Navigation("LtynCt_HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
